# Generated by Django 4.2 on 2023-06-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name_plural': '1. Albums'},
        ),
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name_plural': '2. Photos'},
        ),
        migrations.AddField(
            model_name='photos',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.album'),
        ),
    ]
