# Generated by Django 4.2 on 2023-06-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_album_options_alter_photos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_image',
            field=models.ImageField(null=True, upload_to='album_images/'),
        ),
    ]
