# Generated by Django 4.2 on 2023-06-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_album_album_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_image',
            new_name='album_img',
        ),
    ]
