# Generated by Django 4.2 on 2023-06-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_album_image_album_album_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_img',
            new_name='album_image',
        ),
    ]
