# Generated by Django 4.2 on 2023-06-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_album_img_album_album_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
